std = "lua53"

globals = {
  "_path",
  "audio",
  "cleanup",
  "enc",
  "engine",
  "grid",
  "include",
  "internal_engine",
  "internal_notes_pending",
  "init",
  "key",
  "metro",
  "midi",
  "n808_voice",
  "n303_apply_deck",
  "n303_patch_for_genre",
  "nchord_apply_deck",
  "nchord_patch_for_genre",
  "nchord_voice_notes",
  "nmono_apply_deck",
  "nmono_patch_for_genre",
  "nmono_role_defaults",
  "output_router",
  "params",
  "redraw",
  "screen",
  "sampler_playback_settings",
  "sampler_advanced_tick",
  "sampler_reset_runtime",
  "sampler_state",
  "sampler_stop_all_loops",
  "softcut",
  "util",
}
